language: node_js

before_script:
  - echo "Start CI"

install:
  - npm ci

jobs:
  include:
    - stage: check
      node_js:
        - 10
        - 8
      script:
        - npm run format
        - npm run lint
    - stage: build
      node_js:
        - 10
        - 8
      script:
        - npm run build:library
        - npm run build:style
    - stage: testCoverage
      node_js:
        - 10
        - 8
      script:
        - npm run test:coverage:report -- --username $CODACY_USERNAME --projectName $CODACY_PROJECT_NAME
    - stage: testVisualTDD
      node_js:
        - 10
        - 8
      script:
        - npm run test:visual:tdd

before_deploy:
  - if [ ! -d dist ]; then npm run build:library ; fi
  - if [ ! -d dist ]; then npm run build:style ; fi

deploy:
  provider: npm
  email: $NPM_AUTHOR_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
    node: 10
