export enum ELightsaberOwners {
  ANAKIN_SKYWALKER = 'ANAKIN_SKYWALKER',
  DARTH_MAUL = 'DARTH_MAUL',
  DARTH_SIDIOUS = 'DARTH_SIDIOUS',
  DARTH_VADER = 'DARTH_VADER',
  KYLO_REN = 'KYLO_REN',
  LOWBACCA = 'LOWBACCA',
  LUKE_SKYWALKER = 'LUKE_SKYWALKER',
  MACE_WINDU = 'MACE_WINDU',
  MARA_JADE_SKYWALKER = 'MARA_JADE_SKYWALKER',
  OBI_WAN = 'OBI_WAN',
  PLO_KOON = 'PLO_KOON',
  PRE_VIZSLA = 'PRE_VIZSLA',
  QIU_GON_JINN = 'QIU_GON_JINN',
  QU_RAHN = 'QU_RAHN',
  TERA_SINUBE = 'TERA_SINUBE',
  YADDLE = 'YADDLE',
  YARAEL_POOF = 'YARAEL_POOF',
  YODA = 'YODA',
}

export enum ELightsaberColorClassname {
  CALM = 'calm',
  EVIL = 'evil',
  INTRIGUE = 'intrigue',
  JUSTICE = 'justice',
  MORAL = 'moral',
  NEGOCIATION = 'negociation',
  OBEDIENCE = 'obedience',
  PEACE = 'peace',
  PHYSICAL = 'physical',
  SELF = 'self',
  STRENGTH = 'strength',
}

export const LIGHTSABER_COLOR_CLASSNAME_MAPPING = {
  [ELightsaberOwners.ANAKIN_SKYWALKER]: ELightsaberColorClassname.JUSTICE,
  [ELightsaberOwners.DARTH_MAUL]: ELightsaberColorClassname.EVIL,
  [ELightsaberOwners.DARTH_SIDIOUS]: ELightsaberColorClassname.EVIL,
  [ELightsaberOwners.DARTH_VADER]: ELightsaberColorClassname.EVIL,
  [ELightsaberOwners.KYLO_REN]: ELightsaberColorClassname.EVIL,
  [ELightsaberOwners.LOWBACCA]: ELightsaberColorClassname.PHYSICAL,
  [ELightsaberOwners.LUKE_SKYWALKER]: ELightsaberColorClassname.PEACE,
  [ELightsaberOwners.MACE_WINDU]: ELightsaberColorClassname.MORAL,
  [ELightsaberOwners.MARA_JADE_SKYWALKER]: ELightsaberColorClassname.MORAL,
  [ELightsaberOwners.OBI_WAN]: ELightsaberColorClassname.JUSTICE,
  [ELightsaberOwners.PLO_KOON]: ELightsaberColorClassname.INTRIGUE,
  [ELightsaberOwners.PRE_VIZSLA]: ELightsaberColorClassname.SELF,
  [ELightsaberOwners.QIU_GON_JINN]: ELightsaberColorClassname.PEACE,
  [ELightsaberOwners.QU_RAHN]: ELightsaberColorClassname.STRENGTH,
  [ELightsaberOwners.TERA_SINUBE]: ELightsaberColorClassname.CALM,
  [ELightsaberOwners.YADDLE]: ELightsaberColorClassname.NEGOCIATION,
  [ELightsaberOwners.YARAEL_POOF]: ELightsaberColorClassname.INTRIGUE,
  [ELightsaberOwners.YODA]: ELightsaberColorClassname.PEACE,
} as { [key: string]: string }
